#!/usr/bin/env bash
# 7.0
sudo yum -y install https://repo.ius.io/ius-release-el7.rpm https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm &&
  sudo yum -y install epel-release &&
  sudo rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm &&
  sudo yum clean all &&
  sudo yum makecache &&
  sudo yum -y install php70w.x86_64 && sudo yum list | grep "php70w-" | awk '{if(NR>2)print $1}' | xargs yum install -y --skip-broken
